name: Deploy.yml

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development
        run: echo "Deploying to Development Environment..."

  deploy-qa:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to QA
        run: echo "Deploying to QA Environment..."

  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production Environment..."
