
name: CI Checks

on:
  pull_request:
    branches: [main, dev, qa, prod]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Linter
        run: echo "Linting code..."  # Replace with actual linter if available

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Tests
        run: echo "Running tests..."  # Replace with real test command

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Project
        run: echo "Building project..."  # Replace with real build command
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run tests
        run: |
          echo "Run your tests here"
          # pytest or unittest

