name: Commit Lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit messages from PR
        run: |
          PR_COMMITS=$(git log origin/${{ github.event.pull_request.base.ref }}..HEAD --pretty=format:"%s")
          echo "$PR_COMMITS" > commits.txt

          echo "Checking commit messages..."
          invalid=0
          while IFS= read -r line; do
            if [[ ! "$line" =~ ^(feat|fix)(\([^)]+\))?:\  ]]; then
              echo "❌ Invalid commit message: $line"
              invalid=1
            else
              echo "✅ Valid: $line"
            fi
          done < commits.txt

          if [[ $invalid -eq 1 ]]; then
            echo "Some commit messages are invalid."
            exit 1
          fi
