name: Commit Lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit messages
        run: |
          COMMITS=$(git log origin/${{ github.event.pull_request.base.ref }}..HEAD --pretty=format:"%s")
          echo "$COMMITS" > commits.txt

          echo "Checking commit messages..."
          invalid=0
          while IFS= read -r line; do
            if [[ ! "$line" =~ ^(feat|fix)(\([^)]+\))?:\  ]]; then
              echo "❌ Invalid commit: $line"
              invalid=1
            else
              echo "✅ Valid: $line"
            fi
          done < commits.txt

          if [[ $invalid -eq 1 ]]; then
            echo "❌ Commit format check failed."
            exit 1
          else
            echo "✅ All commits are valid."

